(elscreen-start)
(setq elscreen-tab-display-kill-screen nil)
(setq elscreen-display-screen-number nil)
(setq elscreen-tab-display-control nil)
					; (require 'elscreen-server)
(set-face-background  'elscreen-tab-background-face "#fdf6e3")
(set-face-background  'elscreen-tab-other-screen-face "#fdf6e3")
(set-face-foreground  'elscreen-tab-other-screen-face "#586e75")
(set-face-underline-p 'elscreen-tab-other-screen-face nil)
(set-face-background  'elscreen-tab-current-screen-face "#586e75")
(set-face-foreground  'elscreen-tab-current-screen-face "#fdf6e3")
(set-face-underline-p 'elscreen-tab-current-screen-face nil)
(set-face-bold-p      'elscreen-tab-current-screen-face t)

(set-face-background 'ac-candidate-face "#eee8d5")
(set-face-foreground 'ac-candidate-face "#586e75")
(set-face-background 'ac-selection-face "#586e75")
(set-face-foreground 'ac-selection-face "#fdf6e3")

(global-set-key (kbd "C-z C-z") 'helm-elscreen)
